spring.application.name=gym-crm

# Ensure that initialization scripts are executed
spring.sql.init.mode=always

# Actuator Configs:
#TODO: add actuator things!!!

# Spring Boot Profiles Config
spring.profiles.active=dev

spring.jpa.show-sql=true

# Default logging level (can be overridden in profile-specific files if needed)
logging.level.root=INFO

